### ISSUE TITLE
Use with elm-effects and Effects.tick

### ISSUE THREAD

**Issue by ghost** [mgold/elm-animation#1]
I'm slowly coming up to speed with my Elm / typing / functional fu, and am currently trying to grok Evan's  `Effects` and your `animation`. Were there some technical reasons why `Effects.tick` was not suitable for `animation`? 

Thanks!

**Comment by mgold** [comment]
The biggest problem is that the animation library is built around the idea of a single, always-running clock. Components that encapsulate effects, _by definition_, cannot share a clock. As you add more components, each will have its own clock. It's extra bookkeeping to run these individual clocks only when needed. Furthermore, if you wire up the signals yourself you can use `Time.fps n` to limit the framerate, but with `elm-effects` you're stuck with a wrapper around `requestAnimationFrame`.

That said, you can just eat all that cost and it still works. Here's **[a gist](https://gist.github.com/mgold/399923b7acd29b236b3b)** of the `SpinSquare` example, and yes, both squares can be spinning at the same time. More information in the gist itself.

Every "real" (not a side project or school assignment) 2D and 3D graphics engine I know of uses a single event loop. Using the animation library, you can encapsulate the animation to the component but break out the time to the main event loop, perhaps passing it to `view` and `update`.

Does this answer your question?

**Comment by ghost** [comment]
Yes, very clearly. The gist looks very nice.

Thank you!

**Comment by mgold** [comment]
You're welcome. Glad I could help.

**Comment by jvoigtlaender** [comment]
Just for the record, in case anyone comes back to this later:

Some points from Max's [comment above](https://github.com/mgold/elm-animation/issues/1#issuecomment-143073523) are not applicable criticisms of `elm-effects` anymore. Since the merging of https://github.com/evancz/elm-effects/pull/24 (and, relatedly, for users of `start-app`, https://github.com/evancz/start-app/pull/28) it is not true that "Components that encapsulate effects, by definition, cannot share a clock." Due to the changes pointed to, users of `elm-effects` can now encapsulate effects in components but automatically get efficient interplay in the sense that they are run on a shared clock. Essentially, due to the batching of ticks that was introduced there, one can get a "single event loop" even with separately specified components.

**Comment by mgold** [comment]
If I understand correctly, that's an internal change so that multiple components requesting the animation frame are batched together. In Elm, _each component_ still needs to store its own copy of the clock and continuously request new clock values (as opposed to the whole program once). I think a much better API would be to provide, perhaps to StartApp, a view function that takes the current elapsed time as an argument and is called every animation frame.

**Comment by jvoigtlaender** [comment]
I'm not sure what you mean by "each component needs to store its own copy of the clock". In the new version of `start-app`+`elm-effects`, 100 batchable ticks together in flight will all get the same clock value. They will be sent to the app's `update`-function in one batch. That `update`-function will call the 100 components' `update`-functions. The results will be put together and passed to the app's `view`-function only once (which will probably call the 100 components' `view`-functions, but the point is that this happens only once, rather then 100 times calling the app's `update`-function, each time only updating one of the 100 components, and the same 100 times calling the app's `view`-function, causing as many bursts of calls to 100 component `view`-functions -- so altogether 100*100 calls of small `view`-functions -- despite the fact that each time 99 of the 100 will have no reason to be called).

It's true that "each component needs to continuously request new clock values", but that's just a consequence of the desire for modularity, isn't it? I'm not even sure what you mean by "the whole program only once requesting a new clock value" (in each round). If the program is made up of 200 components, how does it decide which 100 of them actually do need to be called on the next clock tick? (Maybe the other 100 of the 200 are not running any animations, instead are just waiting for mouse clicks or whatever.) The only way to do this modularly seems to be to make it each component's task to declare that it is waiting for another tick.

Overall, I don't understand the  "much better API" you have in mind. Can you elaborate?

In any case, the earlier comments about the cost of modularity here are not accurate anymore. For example, in the issue that sparked the changes to `start-app` and `elm-effects`, it turned out that what you imply in the gist about the `SpinSquare` example stops being true in the presence of the batching trick. Even if one goes from two to many more squares, things keep working efficiently. (Of course, there is a slowdown with more squares, simply because calculating and drawing 100 squares is more expensive than doing so for two squares. But there is no inherent slowdown as a cost of modularity or "because every component has to run its own clock". That kind of cost has been eliminated by the batching trick, I think.)

**Comment by mgold** [comment]
You know more about the changes to startApp and Effects, so it's possible I'm just wrong here. Which would be great, since what you describe sounds quite reasonable.

>  I'm not even sure what you mean by "the whole program only once requesting a new clock value" (in each round). If the program is made up of 200 components, how does it decide which 100 of them actually do need to be called on the next clock tick? 

The premise of the library is that there is a continuously running clock. Without StartApp or Effects, it's just in the model. With them, I am uncertain whether only the app's `update` and model need to track and store the time, or whether each component must define an `Tick Time` case of their action type, and store it in their component model. If the former, that's great and we're done. If the latter, batching the ticks eliminates most of the performance cost because every component is informed of the same clock. I'm concerned about the verbosity of updating and storing the clock in every component.

The "much better API" would be `view : Address action -> Time -> model -> Html`. I don't know if this is feasible, but the intention is to avoid boilerplate in update and Model. Except you'd have to do something similar with the type of `update`, since you need to know the current time when, for example, retargeting an animation on mouse click. So maybe the verbosity is worth it after all.

**Comment by jvoigtlaender** [comment]
@mgold, sorry for not answering earlier here. I have not much to say, since this is not really about right or wrong. There's different approaches. So, just:

> The premise of the library is that there is a continuously running clock. Without StartApp or Effects, it's just in the model. With them, I am uncertain whether only the app's `update` and model need to track and store the time, or whether each component must define an `Tick Time` case of their action type, and store it in their component model.

Each component must define such a case. Whether it needs to store time in their component model depends on what it wants to do with time. Will it be happy to work just with the current time on each `Tick` action, or will it need to compute a difference between the current time and the last time it saw? This can vary.

>  If the latter, batching the ticks eliminates most of the performance cost because every component is informed of the same clock. I'm concerned about the verbosity of updating and storing the clock in every component.

I noticed this concern. But it's not clear this is really a big issue. Benchmarking and/or comparing code would be needed to be sure whether this conceptual and performance overhead is real. For example, if you did the `SpinSquare` example in your approach, but without "cheating" (as you have admitted in the Gist to be doing, and maybe you have also been doing in your mind when thinking about how you would do that example without any `Effects` stuff), you might have to introduce other bookkeeping for starting and stopping clocks/animations, that might be just as verbose etc.

> The "much better API" would be `view : Address action -> Time -> model -> Html`. I don't know if this is feasible, but the intention is to avoid boilerplate in update and Model. Except you'd have to do something similar with the type of `update`, since you need to know the current time when, for example, retargeting an animation on mouse click. So maybe the verbosity is worth it after all.

I've been using such an API in https://github.com/jvoigtlaender/Elm-Kurs, see e.g. the types of `update` and `scene` (my version of `view`) there in https://github.com/jvoigtlaender/Elm-Kurs/blob/master/pages/Ballistics.md, which both take an explicit time argument (as well as an explicit current mouse position argument). But that made sense there because this was just a playground with a fixed set of inputs. If one goes for modularity, I think the approach of `start-app` makes more sense.

But, as said, much of this is too abstract discussion. One would have to compare something concrete realized in the respective APIs to get more real insight.
