### ISSUE TITLE
When trying to run the examples: I cannot find module 'Element'.

### ISSUE THREAD

**Issue by alexander-brett** [mgold/elm-animation#3]
Steps to repro:
- fresh clone of elm-animation HEAD
- start elm-reactor
- visit http://localhost:8000/examples/barChat.elm

```
Downloading elm-lang/core
Packages configured successfully!
I cannot find module 'Element'.

Module 'BarChart' is trying to import it.

Potential problems could be:
  * Misspelled the module name
  * Need to add a source directory or new dependency to elm-package.json
```

Am I doing something wrong or is there something missing in the elm-package.json?

Thanks,
Alex

**Comment by mgold** [comment]
You need to `cd examples` and run the reactor from there.

**Comment by alexander-brett** [comment]
Success. Thank you!

**Comment by ghost** [comment]
I've `cd examples` but it's the same. 😕

**Comment by mgold** [comment]
Try: `git pull && git checkout master && rm -rf elm-stuff && elm package install -y` then `elm reactor`.

**Comment by ghost** [comment]
In both the root folder (`.`) and `examples` I got "`fatal: Not a git repository (or any of the parent directories): .git`". So I `git clone` this repo and it works straight away, without those instructions. I noticed there's no `to-update` directory in the code in this repo, unlike the code from package.elm-lang.org. Is the code on package.elm-lang.org out of sync?

**Comment by mgold** [comment]
Yes, I think I hadn't finished updating the examples when I released. The actual library code is in sync, so I didn't think it warranted a package bump.

You'll want to be on master, which `git clone` takes care of. Since it looks like you got a copy of the source that wasn't a git repo, it sounds like you came from package.elm-lang.org which would have set HEAD as the release tag, and then you downloaded a zip or something. If you want to go that route just be sure you're on master!

**Comment by ghost** [comment]
I had done `elm package install mgold/elm-animation`.
